version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: peticle-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: peticledb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - peticle-network

volumes:
  mysql-data:

networks:
  peticle-network:
