/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/admin/admin_login`; params?: Router.UnknownInputParams; } | { pathname: `/admin/admin_main`; params?: Router.UnknownInputParams; } | { pathname: `/admin/admin_phonenumber`; params?: Router.UnknownInputParams; } | { pathname: `/admin/admin_privacy`; params?: Router.UnknownInputParams; } | { pathname: `/admin/alarm`; params?: Router.UnknownInputParams; } | { pathname: `/admin/pw_change`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/admin/admin_details/[school]`, params: Router.UnknownInputParams & { school: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/admin_login`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/admin_main`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/admin_phonenumber`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/admin_privacy`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/alarm`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/pw_change`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/admin/admin_details/[school]`, params: Router.UnknownOutputParams & { school: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/admin/admin_login${`?${string}` | `#${string}` | ''}` | `/admin/admin_main${`?${string}` | `#${string}` | ''}` | `/admin/admin_phonenumber${`?${string}` | `#${string}` | ''}` | `/admin/admin_privacy${`?${string}` | `#${string}` | ''}` | `/admin/alarm${`?${string}` | `#${string}` | ''}` | `/admin/pw_change${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/admin/admin_login`; params?: Router.UnknownInputParams; } | { pathname: `/admin/admin_main`; params?: Router.UnknownInputParams; } | { pathname: `/admin/admin_phonenumber`; params?: Router.UnknownInputParams; } | { pathname: `/admin/admin_privacy`; params?: Router.UnknownInputParams; } | { pathname: `/admin/alarm`; params?: Router.UnknownInputParams; } | { pathname: `/admin/pw_change`; params?: Router.UnknownInputParams; } | `/+not-found` | `/admin/admin_details/${Router.SingleRoutePart<T>}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/admin/admin_details/[school]`, params: Router.UnknownInputParams & { school: string | number; } };
    }
  }
}
