spring:
  datasource:
    url: jdbc:mariadb://localhost:${MYSQL_PORT:3306}/PETicle
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate  # 최초 create도 가능, 이후에는 update 권장
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080